// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Siestur.Data;

#nullable disable

namespace SIESTUR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251127040435_AddCriticalIndexe")]
    partial class AddCriticalIndexe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Siestur.Models.DayCounter", b =>
                {
                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<int>("NextNumber")
                        .HasColumnType("integer");

                    b.HasKey("ServiceDate");

                    b.ToTable("DayCounters");
                });

            modelBuilder.Entity("Siestur.Models.OperatorDailyFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AvgServeToCompleteSec")
                        .HasColumnType("double precision");

                    b.Property<double?>("AvgTotalLeadTimeSec")
                        .HasColumnType("double precision");

                    b.Property<Guid>("OperatorUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ServedCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<int?>("WindowMax")
                        .HasColumnType("integer");

                    b.Property<int?>("WindowMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OperatorDailyFacts");
                });

            modelBuilder.Entity("Siestur.Models.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("StartNumberDefault")
                        .HasColumnType("integer");

                    b.Property<string>("TvPublicKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Siestur.Models.SystemState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("LastDailyReset")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("SystemStates");
                });

            modelBuilder.Entity("Siestur.Models.Turn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CalledByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ServedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ServedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SkippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid?>("WindowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("WindowId", "Status");

                    b.HasIndex("Status", "Kind", "Number");

                    b.HasIndex("Status", "Number", "CreatedAt");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("Siestur.Models.TurnFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CallToServeSec")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinalStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ServeToCompleteSec")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ServedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("SkippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TotalLeadTimeSec")
                        .HasColumnType("integer");

                    b.Property<int?>("WaitToCallSec")
                        .HasColumnType("integer");

                    b.Property<int?>("WindowNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDate");

                    b.HasIndex("ServiceDate", "OperatorUserId");

                    b.HasIndex("ServiceDate", "WindowNumber");

                    b.ToTable("TurnFacts");
                });

            modelBuilder.Entity("Siestur.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Siestur.Models.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Siestur.Models.Window", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Windows");
                });

            modelBuilder.Entity("Siestur.Models.WorkerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WindowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EndedAt");

                    b.HasIndex("WindowId", "EndedAt");

                    b.ToTable("WorkerSessions");
                });

            modelBuilder.Entity("Siestur.Models.Turn", b =>
                {
                    b.HasOne("Siestur.Models.Window", "Window")
                        .WithMany()
                        .HasForeignKey("WindowId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Window");
                });

            modelBuilder.Entity("Siestur.Models.WorkerSession", b =>
                {
                    b.HasOne("Siestur.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Siestur.Models.Window", "Window")
                        .WithMany()
                        .HasForeignKey("WindowId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");

                    b.Navigation("Window");
                });
#pragma warning restore 612, 618
        }
    }
}
